version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5436:5432'

volumes:
  db_data: