version: '3.8'

services:
  ewallet-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres:13
    volumes:
      - ./.database/postgres/data:/var/lib/pgsql/16/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: ewallet
    ports:
      - '5436:5432'
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 3s
      retries: 3


