name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.22.x, 1.21.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.6.1

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Unit-test
        run: go test ./tests/unit/ -count=1

      - name: Integration-test
        run: go test ./tests/integration/ -count=1

