name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.5

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify



  tests:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.5

      - name: Go Build
        run: go build -o /dev/null ./...

      - name: Tests
        run: go test ./... -count=1
